### PR TITLE
Add ru_ru.json (Russian)

### PR DESCRIPTION
**Pull request by Alexander317**
Hello! Here's the russian translation of your mod
Feel free to correct me or ask me anything about it, I will answer you and commit changes as soon as I can.

I've been working as a mod translator for quite a while now, so if you like my work, you can consider donating! Thank you! (link in bio)

### CODE REVIEW

**Comment by Sephta** [comment]
@Alexander317 This is so cool that you would randomly find my mod and do this for free. I am releasing a new small update that adds support for new, mod specific, Advancements. How much would it cost to have you translate the Advancements text? I'm willing to pay you for your work and come to an agreement on cost. It would be great if I could merge this into my project alongside translations to those as well.

Here is the [update](https://github.com/Sephta/stal-alloys/commit/27afcc9889159fb39306a61a98a53c76a582b16f)

**Comment by Alexander317** [comment]
Hello! I appreciate your willingness to support me financially! My work is completely free for any mod creator, but if anyone wants to support me and give me a huge motivation to continue my work, I have a Boosty account where you can consider donating: https://boosty.to/alexander317 
Thanks!

Also, I'm going to translate new strings very soon, and this PR will be ready for merging!

**Comment by Sephta** [comment]
Thank you once again, I will look over the changes tomorrow morning and merge it shortly after.

**Comment by Alexander317** [comment]
> Thank you once again, I will look over the changes tomorrow morning and merge it shortly after.

Ok, got it!

**Comment by Sephta** [comment]
@Alexander317 just as a brief update, ill be merging your changes into multiple branches and get an updated jar file built and uploaded to modrinth and curseforge for each version later today and tomorrow after I'm off work. I will also be crediting you in the mod description and the github README. My plan was to link to your github profile. Is that okay with you?

**Comment by Alexander317** [comment]
> @Alexander317 just as a brief update, ill be merging your changes into multiple branches and get an updated jar file built and uploaded to modrinth and curseforge for each version later today and tomorrow. I will also be crediting you in the mod description and the github README. My plan was to link to your github profile. Is that okay with you?

Hello! I'm totally fine with that!

**Pull request merged**
